apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pinepods-backups
  namespace: media
  labels:
    app: pinepods
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: ceph-block
