apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: romm-resources
  namespace: media
  labels:
    app: romm
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: local-path
