apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: romm-redis-ceph
  namespace: media
  labels:
    app: romm
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: ceph-block
