---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: act-runner-token
  namespace: git-system
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    creationPolicy: Owner
  data:
  - secretKey: token
    remoteRef:
      key: gitea-act-runner-token
      property: token
