apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rreading-glasses-secret
  namespace: media
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    creationPolicy: Owner
  data:
  - secretKey: POSTGRES_PASSWORD
    remoteRef:
      key: "rreading-glasses-user-password"
      property: password
  - secretKey: HARDCOVER_AUTH
    remoteRef:
      key: "hardcover-api-token"
      property: token
