---
apiVersion: v1
kind: Service
metadata:
  name: matrix-alertmanager-receiver
  namespace: observability
spec:
  type: ClusterIP
  selector:
    app: matrix-alertmanager-receiver
  ports:
    - name: http
      port: 9088
      targetPort: http
      protocol: TCP
